### ISSUE TITLE
Following the Unix instructions in the README does not work on Mac M1

### ISSUE THREAD

**Issue by johnnybenson** [awslabs/aws-crt-php#51]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Following the Unix instructions in the README does not work on Mac M1. 

After executing `./configure` the make command fails

**SDK version number**
Checkout of `main` branch @ 3942776a8c99209908ee0b287746263725685732

**Platform/OS/Hardware/Device**
- macOS 12.1
- M1
- PHP 8.1 (Homebrew)

**To Reproduce (observed behavior)**
```
➜  Sites git clone --recursive https://github.com/awslabs/aws-crt-php.git
Cloning into 'aws-crt-php'...
remote: Enumerating objects: 593, done.
remote: Counting objects: 100% (267/267), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 593 (delta 165), reused 165 (delta 123), pack-reused 326
Receiving objects: 100% (593/593), 182.62 KiB | 4.35 MiB/s, done.
Resolving deltas: 100% (288/288), done.
Submodule 'crt/aws-crt-ffi' (https://github.com/awslabs/aws-crt-ffi.git) registered for path 'crt/aws-crt-ffi'
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi'...
remote: Enumerating objects: 353, done.
remote: Counting objects: 100% (219/219), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 353 (delta 138), reused 95 (delta 58), pack-reused 134
Receiving objects: 100% (353/353), 94.97 KiB | 2.88 MiB/s, done.
Resolving deltas: 100% (201/201), done.
Submodule path 'crt/aws-crt-ffi': checked out 'aecdb91b85079de6883bc3643428be0f1e61c153'
Submodule 'aws-c-auth' (https://github.com/awslabs/aws-c-auth.git) registered for path 'crt/aws-crt-ffi/crt/aws-c-auth'
Submodule 'aws-c-cal' (https://github.com/awslabs/aws-c-cal.git) registered for path 'crt/aws-crt-ffi/crt/aws-c-cal'
Submodule 'aws-c-common' (https://github.com/awslabs/aws-c-common.git) registered for path 'crt/aws-crt-ffi/crt/aws-c-common'
Submodule 'aws-c-compression' (https://github.com/awslabs/aws-c-compression.git) registered for path 'crt/aws-crt-ffi/crt/aws-c-compression'
Submodule 'aws-c-event-stream' (https://github.com/awslabs/aws-c-event-stream.git) registered for path 'crt/aws-crt-ffi/crt/aws-c-event-stream'
Submodule 'aws-c-http' (https://github.com/awslabs/aws-c-http.git) registered for path 'crt/aws-crt-ffi/crt/aws-c-http'
Submodule 'aws-c-io' (https://github.com/awslabs/aws-c-io.git) registered for path 'crt/aws-crt-ffi/crt/aws-c-io'
Submodule 'aws-checksums' (https://github.com/awslabs/aws-checksums.git) registered for path 'crt/aws-crt-ffi/crt/aws-checksums'
Submodule 'aws-lc' (https://github.com/awslabs/aws-lc.git) registered for path 'crt/aws-crt-ffi/crt/aws-lc'
Submodule 's2n' (https://github.com/awslabs/s2n.git) registered for path 'crt/aws-crt-ffi/crt/s2n'
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-c-auth'...
remote: Enumerating objects: 2411, done.
remote: Counting objects: 100% (783/783), done.
remote: Compressing objects: 100% (497/497), done.
remote: Total 2411 (delta 343), reused 607 (delta 257), pack-reused 1628
Receiving objects: 100% (2411/2411), 900.59 KiB | 8.58 MiB/s, done.
Resolving deltas: 100% (1414/1414), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-c-cal'...
remote: Enumerating objects: 1724, done.
remote: Counting objects: 100% (366/366), done.
remote: Compressing objects: 100% (186/186), done.
remote: Total 1724 (delta 194), reused 289 (delta 155), pack-reused 1358
Receiving objects: 100% (1724/1724), 394.33 KiB | 7.44 MiB/s, done.
Resolving deltas: 100% (1032/1032), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-c-common'...
remote: Enumerating objects: 13278, done.
remote: Counting objects: 100% (1673/1673), done.
remote: Compressing objects: 100% (849/849), done.
remote: Total 13278 (delta 946), reused 1376 (delta 743), pack-reused 11605
Receiving objects: 100% (13278/13278), 3.37 MiB | 10.04 MiB/s, done.
Resolving deltas: 100% (8684/8684), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-c-compression'...
remote: Enumerating objects: 538, done.
remote: Counting objects: 100% (157/157), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 538 (delta 61), reused 90 (delta 26), pack-reused 381
Receiving objects: 100% (538/538), 155.92 KiB | 4.45 MiB/s, done.
Resolving deltas: 100% (243/243), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-c-event-stream'...
remote: Enumerating objects: 831, done.
remote: Counting objects: 100% (141/141), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 831 (delta 71), reused 78 (delta 35), pack-reused 690
Receiving objects: 100% (831/831), 276.54 KiB | 4.85 MiB/s, done.
Resolving deltas: 100% (451/451), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-c-http'...
remote: Enumerating objects: 6535, done.
remote: Counting objects: 100% (1115/1115), done.
remote: Compressing objects: 100% (379/379), done.
remote: Total 6535 (delta 709), reused 940 (delta 575), pack-reused 5420
Receiving objects: 100% (6535/6535), 2.94 MiB | 8.87 MiB/s, done.
Resolving deltas: 100% (4503/4503), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-c-io'...
remote: Enumerating objects: 5180, done.
remote: Counting objects: 100% (5180/5180), done.
remote: Compressing objects: 100% (1663/1663), done.
remote: Total 5180 (delta 3374), reused 4846 (delta 3117), pack-reused 0
Receiving objects: 100% (5180/5180), 3.36 MiB | 14.04 MiB/s, done.
Resolving deltas: 100% (3374/3374), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-checksums'...
remote: Enumerating objects: 528, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 528 (delta 34), reused 65 (delta 16), pack-reused 427
Receiving objects: 100% (528/528), 177.46 KiB | 3.86 MiB/s, done.
Resolving deltas: 100% (213/213), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-lc'...
remote: Enumerating objects: 77617, done.
remote: Counting objects: 100% (143/143), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 77617 (delta 74), reused 34 (delta 16), pack-reused 77474
Receiving objects: 100% (77617/77617), 99.99 MiB | 16.20 MiB/s, done.
Resolving deltas: 100% (55419/55419), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/s2n'...
remote: Enumerating objects: 40211, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 40211 (delta 22), reused 16 (delta 8), pack-reused 40147
Receiving objects: 100% (40211/40211), 20.05 MiB | 17.43 MiB/s, done.
Resolving deltas: 100% (28608/28608), done.
Submodule path 'crt/aws-crt-ffi/crt/aws-c-auth': checked out '61b6524960ad5e0c7aa2e38b343425d5941781bf'
Submodule path 'crt/aws-crt-ffi/crt/aws-c-cal': checked out 'aa89aa4950074babe84762413f39bd364ecaf944'
Submodule path 'crt/aws-crt-ffi/crt/aws-c-common': checked out 'fdd4a10243903260f412f587cc748f0ac79629b4'
Submodule 'litani' (https://github.com/awslabs/aws-build-accumulator) registered for path 'crt/aws-crt-ffi/crt/aws-c-common/verification/cbmc/litani'
Submodule 'cbmc-templates' (https://github.com/awslabs/aws-templates-for-cbmc-proofs.git) registered for path 'crt/aws-crt-ffi/crt/aws-c-common/verification/cbmc/templates'
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-c-common/verification/cbmc/litani'...
remote: Enumerating objects: 1219, done.
remote: Counting objects: 100% (485/485), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 1219 (delta 340), reused 382 (delta 274), pack-reused 734
Receiving objects: 100% (1219/1219), 296.23 KiB | 6.30 MiB/s, done.
Resolving deltas: 100% (774/774), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/aws-c-common/verification/cbmc/templates'...
remote: Enumerating objects: 645, done.
remote: Counting objects: 100% (375/375), done.
remote: Compressing objects: 100% (241/241), done.
remote: Total 645 (delta 255), reused 200 (delta 134), pack-reused 270
Receiving objects: 100% (645/645), 147.95 KiB | 4.00 MiB/s, done.
Resolving deltas: 100% (401/401), done.
Submodule path 'crt/aws-crt-ffi/crt/aws-c-common/verification/cbmc/litani': checked out '8b23cb74d5ca47e0f94ee50bb3da7e907fd48f27'
Submodule path 'crt/aws-crt-ffi/crt/aws-c-common/verification/cbmc/templates': checked out '41c333ad41ef8fa4ad1b5573ddfc964c8bd2b4a7'
Submodule path 'crt/aws-crt-ffi/crt/aws-c-compression': checked out 'fc1631ea1ce563b0a453cb7a7233fca949e36970'
Submodule path 'crt/aws-crt-ffi/crt/aws-c-event-stream': checked out 'e87537be561d753ec82e783bc0929b1979c585f8'
Submodule path 'crt/aws-crt-ffi/crt/aws-c-http': checked out 'fa1692ae103dcc40e3d0a9db1b29acfc204a294e'
Submodule path 'crt/aws-crt-ffi/crt/aws-c-io': checked out '14b5e6d73b41eeabf04fc6228276eb1eb59bd99c'
Submodule path 'crt/aws-crt-ffi/crt/aws-checksums': checked out '99bb0ad4b89d335d638536694352c45e0d2188f5'
Submodule path 'crt/aws-crt-ffi/crt/aws-lc': checked out '8b7d44e7c7d0822cb52b92bfa5f92619014cbe31'
Submodule path 'crt/aws-crt-ffi/crt/s2n': checked out 'b5b313b9ccddf268b30c642798f1d2a58d49ecd6'
Submodule 'tests/cbmc/aws-verification-model-for-libcrypto' (https://github.com/awslabs/aws-verification-model-for-libcrypto.git) registered for path 'crt/aws-crt-ffi/crt/s2n/tests/cbmc/aws-verification-model-for-libcrypto'
Submodule 'cbmc-templates' (https://github.com/awslabs/aws-templates-for-cbmc-proofs) registered for path 'crt/aws-crt-ffi/crt/s2n/tests/cbmc/templates'
Submodule 'tests/litani' (https://github.com/awslabs/aws-build-accumulator) registered for path 'crt/aws-crt-ffi/crt/s2n/tests/litani'
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/s2n/tests/cbmc/aws-verification-model-for-libcrypto'...
remote: Enumerating objects: 194, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 194 (delta 123), reused 76 (delta 39), pack-reused 0
Receiving objects: 100% (194/194), 72.22 KiB | 3.14 MiB/s, done.
Resolving deltas: 100% (123/123), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/s2n/tests/cbmc/templates'...
remote: Enumerating objects: 645, done.
remote: Counting objects: 100% (375/375), done.
remote: Compressing objects: 100% (241/241), done.
remote: Total 645 (delta 255), reused 200 (delta 134), pack-reused 270
Receiving objects: 100% (645/645), 147.95 KiB | 6.16 MiB/s, done.
Resolving deltas: 100% (401/401), done.
Cloning into '/Users/johnny/Sites/aws-crt-php/crt/aws-crt-ffi/crt/s2n/tests/litani'...
remote: Enumerating objects: 1219, done.
remote: Counting objects: 100% (485/485), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 1219 (delta 340), reused 382 (delta 274), pack-reused 734
Receiving objects: 100% (1219/1219), 296.23 KiB | 6.30 MiB/s, done.
Resolving deltas: 100% (774/774), done.
Submodule path 'crt/aws-crt-ffi/crt/s2n/tests/cbmc/aws-verification-model-for-libcrypto': checked out '42caa4790273b37cbdf303427b53f445ab1b3480'
Submodule path 'crt/aws-crt-ffi/crt/s2n/tests/cbmc/templates': checked out '7fdd7048b01e68fd549e20da1d216e34d719043a'
Submodule path 'crt/aws-crt-ffi/crt/s2n/tests/litani': checked out 'ea0a5ce88ecccc9a75bdf8790921f11f5c76f17a'
➜  Sites cd aws-crt-php
➜  aws-crt-php git:(main) phpize
Configuring for:
PHP Api Version:         20210902
Zend Module Api No:      20210902
Zend Extension Api No:   420210902
configure.ac:18: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
build/php.m4:2111: PHP_CONFIG_NICE is expanded from...
configure.ac:18: the top level
configure.ac:161: warning: The macro `AC_LANG_C' is obsolete.
configure.ac:161: You should run autoupdate.
./lib/autoconf/c.m4:72: AC_LANG_C is expanded from...
build/libtool.m4:2739: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2738: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: The macro `AC_LANG_C' is obsolete.
configure.ac:161: You should run autoupdate.
./lib/autoconf/c.m4:72: AC_LANG_C is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/libtool.m4:561: _LT_AC_LOCK is expanded from...
build/libtool.m4:1185: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2739: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2738: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:161: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/libtool.m4:561: _LT_AC_LOCK is expanded from...
build/libtool.m4:1185: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2739: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2738: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: \`$CC' does not support \`-c -o', so \`make -j' may be unsafe
build/libtool.m4:1185: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2739: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2738: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: \`$CC' does not support \`-c -o', so \`make -j' may be unsafe
build/libtool.m4:1185: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2739: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2738: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: output file \`$ofile' does not exist
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: output file \`$ofile' does not exist
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: output file \`$ofile' does not look like a libtool script
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: output file \`$ofile' does not look like a libtool script
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: using \`LTCC=$LTCC', extracted from \`$ofile'
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: using \`LTCC=$LTCC', extracted from \`$ofile'
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: tag name \"$tagname\" already exists
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: The macro `AC_LANG_CPLUSPLUS' is obsolete.
configure.ac:161: You should run autoupdate.
./lib/autoconf/c.m4:262: AC_LANG_CPLUSPLUS is expanded from...
build/libtool.m4:2821: _LT_AC_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:2820: AC_LIBTOOL_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: \`$CC' does not support \`-c -o', so \`make -j' may be unsafe
build/libtool.m4:1185: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2821: _LT_AC_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:2820: AC_LIBTOOL_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: \`$CC' does not support \`-c -o', so \`make -j' may be unsafe
build/libtool.m4:1185: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2821: _LT_AC_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:2820: AC_LIBTOOL_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:1929: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
➜  aws-crt-php git:(main) ./configure
./configure: line 655: test: too many arguments
./configure: line 655: test: too many arguments
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... no
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether cc accepts -g... yes
checking for cc option to enable C11 features... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... aarch64-apple-darwin21.2.0
checking host system type... aarch64-apple-darwin21.2.0
checking target system type... aarch64-apple-darwin21.2.0
checking for PHP prefix... /opt/homebrew/Cellar/php/8.1.0
checking for PHP includes... -I/opt/homebrew/Cellar/php/8.1.0/include/php -I/opt/homebrew/Cellar/php/8.1.0/include/php/main -I/opt/homebrew/Cellar/php/8.1.0/include/php/TSRM -I/opt/homebrew/Cellar/php/8.1.0/include/php/Zend -I/opt/homebrew/Cellar/php/8.1.0/include/php/ext -I/opt/homebrew/Cellar/php/8.1.0/include/php/ext/date/lib
checking for PHP extension directory... /opt/homebrew/Cellar/php/8.1.0/pecl/20210902
checking for PHP installed headers prefix... /opt/homebrew/Cellar/php/8.1.0/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking for AWS Common Runtime support... yes, shared
checking for a sed that does not truncate output... /usr/bin/sed
checking for ld used by cc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 786432
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin21.2.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
➜  aws-crt-php git:(main) make && make test
cmake -DCMAKE_INSTALL_PREFIX=build/install -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_OPENSSL=ON  -Hcrt/aws-crt-ffi -Bbuild/aws-crt-ffi-static -DBUILD_SHARED_LIBS=OFF
make: cmake: No such file or directory
make: *** [build/aws-crt-ffi-static/CMakeCache.txt] Error 1
➜  aws-crt-php git:(main)
```

**Expected behavior**
I expected the instructions in the README to work

**Logs/output**
See Above

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

**Additional context**
I'm just trying to use the AWS PHP SDK and it appears that I can't connect to S3 without the CRT. The [SDK prerequisites](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_requirements.html) do not mention needing the CRT at all. It's most likely something I'm doing incorrectly, but not a lot of information for how to proceed without CRT.

```
Aws\Exception\CommonRuntimeException: AWS Common Runtime for PHP is required to use Signature V4A and multi-region access points.  Please install it using the instructions found at https://github.com/aws/aws-sdk-php/blob/master/CRT_INSTRUCTIONS.md in file /var/www/html/vendor/aws/aws-sdk-php/src/Signature/S3SignatureV4.php on line 105

#0 /var/www/html/vendor/aws/aws-sdk-php/src/Signature/S3SignatureV4.php(48): Aws\Signature\S3SignatureV4->signWithV4a()
#1 /var/www/html/vendor/aws/aws-sdk-php/src/Middleware.php(126): Aws\Signature\S3SignatureV4->signRequest()

```

**Comment by SamRemis** [comment]
@johnnybenson, the CRT is needed for very specific operations within the SDK.  What are you trying to do with S3?

**Comment by johnnybenson** [comment]
Very basic stuff, read / write binary objects to a bucket. Creds are in the environment. I was surprised too that it was asking for the CRT.

```php
        $client = new S3Client([
            'region' => env('AWS_BUCKET_REGION'),
            'version' => 'latest',
        ]);

        $result = $client->getObject([
            'Bucket' => env('AWS_BUCKET'),
            'Key' => $key
        ]);
```

Here's the stack from my getObject call
```sh
Aws\Exception\CommonRuntimeException: AWS Common Runtime for PHP is required to use Signature V4A and multi-region access points.  Please install it using the instructions found at https://github.com/aws/aws-sdk-php/blob/master/CRT_INSTRUCTIONS.md in file /var/www/html/vendor/aws/aws-sdk-php/src/Signature/S3SignatureV4.php on line 105

#0 /var/www/html/vendor/aws/aws-sdk-php/src/Signature/S3SignatureV4.php(48): Aws\Signature\S3SignatureV4->signWithV4a()
#1 /var/www/html/vendor/aws/aws-sdk-php/src/Middleware.php(126): Aws\Signature\S3SignatureV4->signRequest()
#2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\Middleware::Aws\{closure}()
#3 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#4 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#5 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#6 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#8 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /var/www/html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
#11 /var/www/html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient->execute()
#12 /var/www/html/app/Services/CreateS3Client.php(44): Aws\AwsClient->__call()
#13 /var/www/html/app/Services/GetChunkFromS3.php(22): App\Services\CreateS3Client->get()
```

**Comment by SamRemis** [comment]
Ah yes, you do need it if you're using multi region access points.  Since region-less access points are a newer feature, they need to be signed with our latest signing algorithm which uses a hashing algorithm not available in PHP.  If you don't want to use a multi-region access point, (you can still use an access point), you can continue without the CRT.  
Either way, I'll see if I can reproduce this error and figure out what went wrong.  Thanks for bringing this to our attention

**Comment by johnnybenson** [comment]
Awesome thanks for the feedback and for taking a closer look!

**Comment by johnnybenson** [comment]
FWIW, creating and using an access point for the bucket removed the multi-region requirement and the need to install CRT. So I'm on my way, reading and writing objects in `us-east-2` 😎 .

The bug report for installing CRT still stands, could not get it to progress beyond the `make` step.

**Comment by TingDaoK** [comment]
> make: cmake: No such file or directory

Do you have cmake installed?

**Comment by TingDaoK** [comment]
Cmake is required to install the package. It looks like it's missing in your environment. Please install cmake and try again.

**Comment by TingDaoK** [comment]
closing due to inactivity.
